const SIDENAV_FULL = "FULL";
const SIDENAV_COMPACT = "COMPACT";
const SIDENAV_CLOSE = "CLOSE";
const SIDENAV_MOBILE = "MOBILE";
const SET_USER = "SET_USER";

export {
    SIDENAV_CLOSE, SIDENAV_FULL, SIDENAV_COMPACT, SIDENAV_MOBILE, SET_USER
};
